// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mkvjsE-omHMvTwpy3XBqCWPb1jKNRCk',
    appId: '1:276760323209:web:149cf2558721b438e05258',
    messagingSenderId: '276760323209',
    projectId: 'convo-5',
    authDomain: 'convo-5.firebaseapp.com',
    storageBucket: 'convo-5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClJSFTwT3oozGdRTmp7iL07OnNw63efyc',
    appId: '1:276760323209:android:7ab64bb5d8840dd6e05258',
    messagingSenderId: '276760323209',
    projectId: 'convo-5',
    storageBucket: 'convo-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yKwVMGN5qJxxZoCK5uis0VJHTmoLeFI',
    appId: '1:276760323209:ios:82da815fdbb19d52e05258',
    messagingSenderId: '276760323209',
    projectId: 'convo-5',
    storageBucket: 'convo-5.appspot.com',
    iosBundleId: 'com.example.convo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yKwVMGN5qJxxZoCK5uis0VJHTmoLeFI',
    appId: '1:276760323209:ios:82da815fdbb19d52e05258',
    messagingSenderId: '276760323209',
    projectId: 'convo-5',
    storageBucket: 'convo-5.appspot.com',
    iosBundleId: 'com.example.convo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8mkvjsE-omHMvTwpy3XBqCWPb1jKNRCk',
    appId: '1:276760323209:web:8fe1afa94dd7be50e05258',
    messagingSenderId: '276760323209',
    projectId: 'convo-5',
    authDomain: 'convo-5.firebaseapp.com',
    storageBucket: 'convo-5.appspot.com',
  );

}